<?php include_once($_SERVER['DOCUMENT_ROOT'] . '/templates/components/header.php'); ?>
<!-- extra css here -->
<?php include_once($_SERVER['DOCUMENT_ROOT'] . '/templates/components/head.php') ?>

	<header>
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		  <a class="navbar-brand" href="/">Quizzy Rascal</a>
		</nav>
	</header>

    <!-- Begin page content -->
    <main role="main" class="container">
		<div id="app">
			<h1>Hello, Mole</h1>
		</div>
    </main>

<?php include_once($_SERVER['DOCUMENT_ROOT'] . '/templates/components/footer.php') ?>
<!-- extra js here -->
<?php include_once($_SERVER['DOCUMENT_ROOT'] . '/templates/components/foot.php') ?>
